unstable_features = true
blank_lines_upper_bound = 2
chain_width = 20
combine_control_expr = false
comment_width = 80
wrap_comments = true
imports_layout = "HorizontalVertical"
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_try_shorthand = true
